write_section_task:
  description: >
    Write a comprehensive section on the topic: "{topic}" to post on linked in.
    Target audience: {audience_level} level readers on Linked In.
    Make sure you find any interesting and latest relevant information.
    For your refference, current year: {current_year}
    Your content should:
    1. Begin with a brief introduction to the section topic
    2. Explain all key concepts clearly with examples
    3. Include practical applications or exercises where appropriate
    4. End with a summary of key points
    5. Be approximately 2500-3500 words in length depends upon the topic, complexity and audience level, but ensure 2500 words minimum.
  expected_output: >
    A well-structured, comprehensive section in Markdown format that thoroughly
    explains the {topic} and is appropriate for the target audience.
  agent: content_writer

review_section_task:
  description: >
    Review and improve the generated content on "{topic}":

    Target audience: {audience_level} level readers on Linked In.

    Latest Year: {current_year}

    Your review should:
    1. Fix any grammatical or spelling errors
    2. Improve clarity and readability
    3. Ensure content is comprehensive and accurate
    4. Verify consistency with previously written sections
    5. Enhance the structure and flow
    6. Add any missing key information
    7. Ensure the content is engaging and informative
    8. Make sure the format of the content follow the Markdown style guide

    Provide the improved version of the section in Markdown format.
  expected_output: >
    An improved, polished version of the section in markdown format that maintains the original structure but enhances clarity, accuracy, and consistency.
  agent: content_editor
  dependencies: [write_section_task]

markdown_formatting_task:
  description: >
    Review the content on "{topic}" and make sure it is formatted correctly in Markdown:
    Your task is to ensure that the content adheres to Markdown syntax and best
    practices. This includes checking for proper use of headings, lists, code
    blocks, links, images, and tables. Ensure that the document is visually
    appealing and easy to read. The content should be well-structured and
    follow best practices for Markdown formatting. Check for any missing or
    incorrect formatting elements. The content should be clear, concise, and
    easy to navigate. Ensure that the formatting enhances the readability and
    usability of the document. The formatting should not
    detract from the content but rather enhance it. The document should be
    polished and professional, ready for publication.

    Your version must ensure below points:
    1. Ensure proper Markdown syntax is used throughout the document
    2. Check for consistent use of headings, lists, and code blocks
    3. Ensure proper formatting of links, images, and tables
    4. Verify that the document is visually appealing and easy to read
    5. Ensure that the content is well-structured and follows best practices for Markdown formatting
    6. Check for any missing or incorrect formatting elements

    Provide the improved version of the section in Markdown format.
  expected_output: >
    A well-formatted version of the section in Markdown format that adheres to
    best practices and enhances readability and usability.
  agent: markdown_formatter
  dependencies: [review_section_task]
